"""PR-034 add subscriptions and billing records

Revision ID: 264a5494e090
Revises: 82b660683587
Create Date: 2026-08-14 05:38:29.050643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264a5494e090'
down_revision: Union[str, Sequence[str], None] = '82b660683587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_current_period_end', 'subscriptions', ['current_period_end'], unique=False)
    op.create_index('ix_subscriptions_customer_id', 'subscriptions', ['customer_id'], unique=False)
    op.create_index('ix_subscriptions_organisation_id', 'subscriptions', ['organisation_id'], unique=False)
    op.create_index('ix_subscriptions_plan_id', 'subscriptions', ['plan_id'], unique=False)
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_table('billing_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_billing_records_billing_period_end', 'billing_records', ['billing_period_end'], unique=False)
    op.create_index('ix_billing_records_customer_id', 'billing_records', ['customer_id'], unique=False)
    op.create_index('ix_billing_records_organisation_id', 'billing_records', ['organisation_id'], unique=False)
    op.create_index('ix_billing_records_plan_id', 'billing_records', ['plan_id'], unique=False)
    op.create_index('ix_billing_records_status', 'billing_records', ['status'], unique=False)
    op.create_index('ix_billing_records_subscription_id', 'billing_records', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_billing_records_subscription_id', table_name='billing_records')
    op.drop_index('ix_billing_records_status', table_name='billing_records')
    op.drop_index('ix_billing_records_plan_id', table_name='billing_records')
    op.drop_index('ix_billing_records_organisation_id', table_name='billing_records')
    op.drop_index('ix_billing_records_customer_id', table_name='billing_records')
    op.drop_index('ix_billing_records_billing_period_end', table_name='billing_records')
    op.drop_table('billing_records')
    op.drop_index('ix_subscriptions_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_plan_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_organisation_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_customer_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_current_period_end', table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
