"""PR-010: Add organisation member indexes

Revision ID: 4775363f8f8d
Revises: 8db34ea36707
Create Date: 2026-08-08 18:59:35.914213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4775363f8f8d'
down_revision: Union[str, Sequence[str], None] = '8db34ea36707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_org_member_organisation_id', 'organisation_members', ['organisation_id'], unique=False)
    op.create_index('ix_org_member_role_id', 'organisation_members', ['role_id'], unique=False)
    op.create_index('ix_org_member_user_id', 'organisation_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_org_member_user_id', table_name='organisation_members')
    op.drop_index('ix_org_member_role_id', table_name='organisation_members')
    op.drop_index('ix_org_member_organisation_id', table_name='organisation_members')
    # ### end Alembic commands ###
